name: Reddit Highlights (daily 19:00 CET/CEST)

on:
  schedule:
    # 17:00 UTC = 19:00 Europe/Warsaw ( CET, and CEST)
    - cron: "30 18 * * *"
    # (option) bufor 5 minutes
    - cron: "35 18 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: (scheduled)
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          REDDIT_USER_AGENT: "highlights-bot/1.0 by u/${{ secrets.REDDIT_USERNAME }}"

          SOURCE_SUBREDDIT: "CShortDramas"
          TARGET_SUBREDDIT: "MyHighlightBotTests"

          SCAN_LIMIT: "1500"
          MIN_SCORE: "0"
          DRY_RUN: "false"        # false = post, true = view only
          DEBUG: "true"
          TIMEZONE: "Europe/Warsaw"

          SHOW_THUMBNAILS: "false"

          HIGHLIGHTS_FLAIR: "Community Highlights"   
          
          DRAMA_REVIEW_LIMIT: "7"
          DISCUSSIONS_LIMIT: "7"
          
          STICKY: "true"
          STICKY_POSITION: "bottom"
          SUGGESTED_SORT: "confidence"
        run: |
          python -u reddit_highlights_bot.py


