on:
  schedule:
    # 17:00 UTC = 19:00 Europe/Warsaw (CET/CEST)
    - cron: "30 19 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # … (checkout, setup Pythona, instalacja zależności itd.)
      - name: Run bot
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          REDDIT_USER_AGENT: "highlights-bot/1.0 by Highlight-Bot"
          TIMEZONE: "Europe/Warsaw"
          DRY_RUN: "false"                  # <—— to jest kluczowe
          SOURCE_SUBREDDIT: "CShortDramas"
          TARGET_SUBREDDIT: "MyHighlightBotTests"
          MIN_SCORE: "0"
          SHOW_THUMBNAILS: "false"
          HIGHLIGHTS_FLAIR: "Community Highlights"
          DRAMA_REVIEW_LIMIT: "7"
          DISCUSSIONS_LIMIT: "7"
          STICKY: "true"
          STICKY_POSITION: "bottom"
          SUGGESTED_SORT: "confidence"
        run: |
          python -u reddit_highlights_bot.py
