name: Reddit Highlights (21:30 Europe/Warsaw)

on:
  schedule:
    # 19:30 UTC = 21:30 Europe/Warsaw (CEST)
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: highlights
      cancel-in-progress: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          REDDIT_USER_AGENT: "highlights-bot/1.0 by Highlight-Bot"
          TIMEZONE: "Europe/Warsaw"
          DRY_RUN: "false"
          SOURCE_SUBREDDIT: "CShortDramas"
          TARGET_SUBREDDIT: "MyHighlightBotTests"
          SCAN_LIMIT: "1500"
          MIN_SCORE: "0"
          SHOW_THUMBNAILS: "false"
          HIGHLIGHTS_FLAIR: "Community Highlights"
          DRAMA_REVIEW_LIMIT: "7"
          DISCUSSIONS_LIMIT: "7"
          STICKY: "true"
          STICKY_POSITION: "bottom"
          SUGGESTED_SORT: "confidence"
        run: |
          echo "[TIME] UTC:   $(date -u +'%Y-%m-%d %H:%M')"
          echo "[TIME] Local: $(TZ=Europe/Warsaw date +'%Y-%m-%d %H:%M %Z')"
          python -u reddit_highlights_bot.py
