name: Reddit Highlights — 1× daily after 17:00 (Europe/Warsaw)

on:
  schedule:
    - cron: "*/15 * * * *"   # częste próby przez cały dzień
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: reddit-highlights-daily
      cancel-in-progress: false
    env:
      GATE_HHMM: "1700"   # <— godzina bramkowa w HHMM (Warszawa)

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Debug — pokaż strukturę repo
        run: |
          pwd
          ls -la
          ls -la .github/workflows || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Bramkowanie po 17:00 (Europe/Warsaw) + klucz daty do cache
      - name: Ustal datę i bramkę (Warsaw)
        id: clock
        run: |
          echo "date_key=$(TZ=Europe/Warsaw date +%Y-%m-%d)" >> $GITHUB_OUTPUT
          echo "LOCAL_TIME=$(TZ=Europe/Warsaw date +'%Y-%m-%d %H:%M %Z')" >> $GITHUB_ENV
          echo "UTC_TIME=$(date -u +'%Y-%m-%d %H:%M UTC')"   >> $GITHUB_ENV
          GATE="${GATE_HHMM:-1700}"
          if [ "$(TZ=Europe/Warsaw date +%H%M)" -ge "${GATE}" ]; then
            echo "after_gate=true"  >> $GITHUB_OUTPUT
          else
            echo "after_gate=false" >> $GITHUB_OUTPUT
          fi
          echo "[TIME] Local: $LOCAL_TIME"
          echo "[TIME] UTC:   $UTC_TIME"
          echo "[GATE] using GATE_HHMM=${GATE}"

      - name: Sprawdź flagę „opublikowano dziś”
        id: cache-flag
        uses: actions/cache@v4
        with:
          path: .highlights-state/${{ steps.clock.outputs.date_key }}.txt
          key:  highlights-${{ steps.clock.outputs.date_key }}

      - name: SKIP — przed godziną bramkową
        if: steps.cache-flag.outputs.cache-hit != 'true' && steps.clock.outputs.after_gate == 'false'
        run: echo "Jest ${LOCAL_TIME} — przed ${GATE_HHMM}. Czekam na późniejszy run."

      - name: SKIP — dziś już publikowano
        if: steps.cache-flag.outputs.cache-hit == 'true'
        run: echo "Dzisiejsza publikacja (${{ steps.clock.outputs.date_key }}) już odnotowana — pomijam."

      - name: Run bot (publikuj)
        if: steps.cache-flag.outputs.cache-hit != 'true' && steps.clock.outputs.after_gate == 'true'
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          REDDIT_USER_AGENT: "highlights-bot/1.0 by u/Highlight-Bot"
          TIMEZONE: "Europe/Warsaw"
          DRY_RUN: "false"
          SOURCE_SUBREDDIT: "CShortDramas"          # ← podmień jeśli chcesz
          TARGET_SUBREDDIT: "CShortDramas" # ← podmień jeśli chcesz
          MIN_SCORE: "0"
          SHOW_THUMBNAILS: "false"
          HIGHLIGHTS_FLAIR: "Community Highlights"
          DRAMA_REVIEW_LIMIT: "7"
          DISCUSSIONS_LIMIT: "7"
          STICKY: "true"
          STICKY_POSITION: "bottom"
          SUGGESTED_SORT: "confidence"
        run: |
          set -o pipefail
          echo "[RUN] Odpalam bota o $LOCAL_TIME (Warsaw)."
          python -u ./reddit_highlights_bot.py 2>&1 | tee bot.log

      # Zapisujemy flagę TYLKO jeśli faktycznie było "Posted/Comment added"
      - name: Wykryj, czy faktycznie opublikowano
        id: pubcheck
        if: steps.cache-flag.outputs.cache-hit != 'true' && steps.clock.outputs.after_gate == 'true'
        run: |
          if grep -E "^\[OK\] Posted: https://redd\.it/" bot.log || grep -E "^\[OK\] Comment added under:" bot.log; then
            echo "published=true" >> $GITHUB_OUTPUT
            echo "✅ Wykryto opublikowany post."
          else
            echo "published=false" >> $GITHUB_OUTPUT
            echo "ℹ️ Nie znaleziono sygnału publikacji w logu."
          fi

      - name: Zapisz flagę „opublikowano dziś”
        if: steps.pubcheck.outputs.published == 'true'
        run: |
          mkdir -p .highlights-state
          echo "posted_at_local=$LOCAL_TIME" > .highlights-state/${{ steps.clock.outputs.date_key }}.txt
          echo "posted_at_utc=$UTC_TIME"   >> .highlights-state/${{ steps.clock.outputs.date_key }}.txt
          echo "[DONE] Zapisano znacznik dnia: ${{ steps.clock.outputs.date_key }}"

