name: Reddit Highlights (daily 19:00 CET/CEST)

on:
  schedule:
    - cron: "0 * * * *"   # every hour (UTC)
  workflow_dispatch:       # manual run button

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot (publish only at 19:00 Europe/Warsaw)
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          REDDIT_USER_AGENT: "highlights-bot/1.0 by u/${{ secrets.REDDIT_USERNAME }}"

          SOURCE_SUBREDDIT: "CShortDramas"
          TARGET_SUBREDDIT: "MyHighlightBotTests"   # na start forum testowe
          DRY_RUN: "true"                           # podgląd w logach, nie publikacja
          DEBUG: "false"
          SCAN_LIMIT: "1500"
          TIMEZONE: "Europe/Warsaw"
          SHOW_THUMBNAILS: "false"

          HIGHLIGHTS_FLAIR: ${{ secrets.HIGHLIGHTS_FLAIR }}
          STICKY: "true"
          STICKY_POSITION: "bottom"
          SUGGESTED_SORT: "confidence"
        run: |
          python - << 'PY'
          import os, sys, subprocess, datetime
          from zoneinfo import ZoneInfo

          tz = ZoneInfo(os.getenv("TIMEZONE","Europe/Warsaw"))
          now = datetime.datetime.now(tz)
          print("[INFO] Local time:", now.isoformat())

          if now.hour == 19:
              print("[INFO] It's 19:00 local — running bot.")
              rc = subprocess.call([sys.executable, "reddit_highlights_bot.py"])
              sys.exit(rc)
          else:
              print("[SKIP] Not 19:00 local — skipping.")
              sys.exit(0)
          PY

